### ISSUE TITLE
Try to implement the TensorFlow version control in my code

### ISSUE THREAD

**Issue by carlosuc3m** [imagej/imagej-tensorflow#26]
Hello, I am trying to implement the control of tf versions in my code using the functionality added to ImageJ-TensorFlow. I am having some trouble as I do not know how to tackle it.
Could you please provide some guidelines to do it?
Regards,
Carlos

**Comment by frauzufall** [comment]
Hi Carlos,

I wrote up how to integrate the TensorFlow versioning handling in [this forum post](https://forum.image.sc/t/imagej-tensorflow-now-with-command-to-change-tensorflow-library-version-switch-to-gpu/31744). 

Let me know if there are issues using that code example.

Best,
Deborah
