### ISSUE TITLE
Cache directory location during development

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-tensorflow#7]
During development, the cache location is set to the directory of the source code in the folder `models`: https://github.com/imagej/imagej-tensorflow/blob/2f6a924c50f79c919c97856a7b5905403c07d009/src/main/java/net/imagej/tensorflow/DefaultTensorFlowService.java#L203

Would that make sense to relocate it to somewhere else? Or at least an option to set the location.

I can work on a PR.

**Comment by ctrueden** [comment]
It is not "the directory of the source code" but rather the base directory of the ImageJ installation. However, when running for source, it will end up being your source folder, yeah. The idea is to mirror ImageJ's other user-configurable folders: e.g., `luts` and `macros` and `scripts`.

An option is fine. I'm curious why you don't like it, though.

**Comment by hadim** [comment]
Only because my code folder is synced on Google Drive. I'll make a PR.

**Comment by ctrueden** [comment]
I'd recommend using a system property like `imagej.models.dir` or some such. Then you can set it in your `~/.m2/settings.xml` without polluting your POM.

**Comment by hadim** [comment]
See #10.

**Comment by frauzufall** [comment]
Closed with this PR https://github.com/imagej/imagej-tensorflow/pull/14
