### ISSUE TITLE
Policy for NN models distribution

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-tensorflow#8]
Does ImageJ have a policy for NN model distribution?

At the moment I am using [GitHub releases](https://github.com/hadim/Fiji_MaskRCNN/releases) to upload neural networks model but I feel like it should not be associated with source code.

**Comment by imagejan** [comment]
How about uploading the model to [zenodo.org](https://zenodo.org/)? It would then get a citable DOI and a unique URL to be used from within your project.

**Comment by ctrueden** [comment]
There is no formal policy. It seems likely that some "model zoo" hosting services will arise that allow people to host their models easily. On the SciJava side, I have no plans (yet) to create or host anything like that on LOCI infrastructure. However, I believe the CellProfiler team at Broad might be interested in doing something like that—at the least, they have interest in helping the community to organize them somehow. /cc @0x00b1

For the [Microscope Focus Quality](https://imagej.net/Microscope_Focus_Quality) plugin, the model is [hosted on Google storage](https://github.com/fiji/microscope-image-quality/blob/microscope-image-quality-0.1.1/src/main/java/sc/fiji/imageFocus/MicroscopeImageFocusQualityClassifier.java#L88-L89).

**Comment by hadim** [comment]
For the record, I plan to use Quilt for model distribution: https://docs.quiltdata.com

I just discovered it and it looks awesome.
